---
output:
  pdf_document:
    latex_engine: xelatex
    template: template.tex
first: Lucy
last: D'Agostino McGowan
email: ld.mcgowan@vanderbilt.edu
address: "2525 West End 11000 Nashville, TN 37203"
website: "www.lucymcgowan.com"
orcid: 0000-0001-7297-9359
languages: proficient Italian literary, written, \& oral skills 
programming: |
  | **dev:** R **use:** R, SAS, Stata, Python, ArcGIS
github: LucyMcGowan
twitter: LucyStats
attributes: "goal-driven leadership, advanced analytic skills, strategic thinking, resourceful team player, sunny disposition $\\Springtree$, public speaking, organizational & communication skills"
interests: "propensity score analyses, `R` package development, observational study methods, predictive modeling, large-scale inference, [R-Ladies](https://rladies.org), engaging beginners in `R` package development with [rOpenSci](http://ropensci.org) through [`contributr`](https://github.com/LucyMcGowan/contributr), disparities research, community-based participatory research"
edu:
  - {degree: PhD, where: Vanderbilt University , description_1: "Student in Biostatistics, GPA 3.95" }
  - {degree: MS, where: Washington University School of Medicine, description_1: "in Biostatistics, December 2013, GPA 3.88 ", description_2: "Thesis: *Quantitative Assessment of the Community Research Fellows Training Program*"}
  - {degree: BA, where: University of North Carolina at Chapel Hill, description_1: "with Distinction and Highest Honors", description_2: "Religious Studies: GPA 3.92 Romance Languages: GPA 3.86"}
work:
  - {year: "March 2017-present", where: RStudio, what: upcoming internship under Jenny Bryan}
  - {year: 2016-2017, where: Vanderbilt University, what: NIH Big Data to Knowledge Training Fellow}
  - {year: 2015-2016, where: Vanderbilt University, what: "Research Assistant, Department of Biostatistics and VA Tennessee Valley"}
  - {year: Summer 2015, where: Cleveland Clinic, what: "Graduate Fellow, Department of Quantitative Health Sciences"}
  - {year: 2012-2014, where: Washington University School of Medicine, what: "Statistical Data Analyst promoted from Research Assistant, Department of Surgery, Division of Public Health Sciences"}
award:
  - {year: 2016, name: "First Place, GSS Student Data Challenge, ASA Joint Statistical Meeting"}
  - {year: 2016, name: "Second Place, SPAAC Poster Competition, ASA Joint Statistical Meeting"}
  - {year: 2016, name: "Southern Startup Internship Program in Data Science (South BDHub)"}
  - {year: 2015, name: "First Place, GSS Student Data Challenge, ASA Joint Statistical Meeting"}
  - {year: 2013, name: "Best Contributed Paper in the Statistics and Data Analysis SAS Global Forum"}
  - {year: 2013, name: "First Place, Student Research Competition, 141st APHA Annual Meeting"}
  - {year: 2013, name: "Ellis R. Ott Scholarship: ASQ Statistics Division"}
  - {year: 2012, name: "Gertrude M. Cox Scholarship for Women in Statistics Honorable Mention"}
outreach: 
  - {year: 2016-2017, name: "R-Ladies Nashville, co-founder"}
  - {year: 2016-2017, name: "Vanderbilt Graduate Student Council, President"}
  - {year: 2016-2017, name: "Vanderbilt Biostatistics Graduate Student Association, Vice President"}
  - {year: 2016-2017, name: "Nashville ASA Student Chapter, Vice President"}
  - {year: 2015-2017, name: "Tennessee Office of Refugees, Tutor"}
  - {year: 2015, name: "Scholarship of Teaching and Learning, Scholar"}
  - {year: 2014-2015, name: "Vanderbilt Graduate Student Council, VP of Social Affairs"}
bibliography: my-papers.bib
csl: apa.csl
nocite: |
  @DAgostinoMcGowan:2013ew, @Colditz:2014hh, @Griffey:2014fa, @DiggsAndrews:2014fb, @Fisher:2014jt,
  @Kaphingst:2015kl, @McGowan:2015bt, @McGowan:2016ira, @Drake:2016ks, @Chen:2015ki
---

# Select Invited Presentations
\vspace{-0.5cm}

**SAS Global Forum 2016** \fn{Oral Presentation} 

> **Lucy D'Agostino McGowan**, Robert A. Greevy, Jr ["Integrating SAS and R to Perform Optimal Propensity Score Matching."](http://support.sas.com/resources/papers/proceedings16/11420-2016.pdf)

**SAS Global Forum 2015** \fn{Oral Presentation}  

> **Lucy D'Agostino McGowan**, Alice Toll ["Using PROC SURVEYREG and PROC SURVEYLOGISTIC to Assess Potential Bias."](http://support.sas.com/resources/papers/proceedings15/3320-2015.pdf)

# Select Contributed Presentations
\vspace{-0.5cm}
**ENAR 2017** \fn{Oral Presentation}  

> **Lucy D'Agostino McGowan**, Robert Alan Greevy, Jr, "Simplifying and Contextualizing Sensitivity to Unmeasured Confounding Tipping Point Analyses."

**ASA Joint Statistical Meeting 2016** \fn{Poster} 

> **Lucy D'Agostino McGowan**, Robert A. Greevy, Jr, "Practical Guidance and Tools for Rule-Out Sensitivity to Unmeasured Confounding Analyses."

# Peer-reviewed Publications 
\vspace{-0.5cm}