---
title: "test"
author: "Lucy D’Agostino McGowan"
date: "3/24/2017"
output:
  pdf_document:
    latex_engine: xelatex
    template: template.tex
first: Lucy
last: D'Agostino McGowan
email: ld.mcgowan@vanderbilt.edu
address: "2525 West End 11000 Nashville, TN 37203"
website: "www.lucymcgowan.com"
orcid: 0000-0001-7297-9359
languages: proficient Italian literary, written, \& oral skills 
programming: "dev: R, \\ use: R, SAS, Stata, Python, ArcGIS" 
github: LucyMcGowan
twitter: LucyStats
bibliography: my-papers.bib
csl: apa.csl
nocite: |
  @DAgostinoMcGowan:2013ew, @Colditz:2014hh, @Griffey:2014fa, @DiggsAndrews:2014fb, @Fisher:2014jt,
  @Kaphingst:2015kl, @McGowan:2015bt, @McGowan:2016ira, @Drake:2016ks, @Chen:2015ki
---

# Interests
ROC methodology, statistical methodology for diagnostic medicine, clinical trials, predictive
modeling, large-scale inference, disparities research, community-based participatory research

# Education
**PhD** Student in Biostatistics, GPA 3.95 \fn{Vanderbilt University}  
Fellow, Big Biomedical Data Science Training, 2016-2017

**MS**  in Biostatistics, December 2013, GPA 3.88 \fn{Washington University School of Medicine}    
Thesis: *Quantitative Assessment of the Community Research Fellows Training Program*

**BA** with Distinction and Highest Honors \fn{University of North Carolina at Chapel Hill}  
Religious Studies: GPA 3.92 Romance Languages: GPA 3.86  
Thesis: *Engaging Catholic Youth Today: High School Youth Ministry in the United States*

**Study Abroad**
Venice, Italy (*Wake Forest University*) Summer 2009  
Rome, Italy (*The Pontifical University of Saint Thomas Aquinas*) Summer 2010  

# Teaching Experience
**Vanderbilt University**  
*Teaching Assistant*  
Regression Modelling Strategies \fn{Spring 2017}  
Statistical Collaboration in Health Sciences \fn{Fall 2015}  
Modern Regression Analysis \fn{Spring 2015}   
Principles of Modern Biostatistics \fn{Fall 2015} 

**Washington University School of Medicine**   
*Teaching Assistant*  
Introduction to Clinical Epidemiology \fn{Fall 2013}  
Randomized Controlled Trials \fn{Fall 2013}  
Introduction to SAS \fn{Spring 2013}  

# Research experience



|               |                                                                | 
|---------------|----------------------------------------------------------------|
|2015-present|**VANDERBILT UNIVERSITY** \fn{Nashville, TN}| 
||*Graduate Research Assistant, Department of Biostatistics and Veteran Affairs*|
|| Perform statistical analyses and large-scale inference on a retrospective national cohort of 411,055 Veterans Health Administration patients. Experience with manipulating and analyzing large datasets, as well as integrating data from multiple sources, such as the National Death Index, Medicare, and Medicaid. Current focus is the association between diabetes medications and congestive heart failure|

\newgeometry{left=2cm,top=2cm,right=2cm,bottom=2.5cm}

#Research experience, continued
|               |                                                                | 
|---------------|----------------------------------------------------------------|
|2015|**CLEVELAND CLINIC** \fn{Cleveland, OH}|
||*Summer Graduate Fellow, Department of Quantitative Health Sciences*|
||Worked under Nancy Obuchowski on multi-reader multi-case ROC analyses. Conducted a examining the effect of location bias in two large MRMC ROC studies, comparing three ROC scoring methods. Compared one method that only uses the maximum confidence score and does not take location bias into account (maxROC), and two methods that take location bias into account: the region of interest ROC (ROI-ROC) and the free-response ROC (FROC).|
|||
|2012--2014|**WASHINGTON UNIVERSITY SCHOOL OF MEDICINE** \fn{St. Louis, MO}|
||*Statistical Data Analyst, Department of Surgery, Division of Public Health Sciences*|
||Began as a research assistant and promoted to statistical data analyst position. Experience in planning and executing analytical projects. Lead survey data manager for Center for Outpatient Health Study focusing on health literacy. Performed statistical analyses including univariate, bivariate, multivariate, and mixed methods. Extensive SAS experience in analyzing large datasets including data step processing, data manipulation, macro creation, data mining, regression analyses, survival analyses, and two-time winner of SAS Student Ambassador award.|
|||
|2012-2014|**GUTMANN RESEARCH LABORATORY** \fn{St. Louis, MO}|
||*Research Assistant, Washington University School of Medicine, Department of Neurology*|
||Performed microarray analysis using programs such as R and Partek to determine unique transcripts. Worked with researchers to prioritize transcripts for validation.|
|||
|Summer 2013|**GRAHAM COLDITZ LABORATORY** \fn{St. Louis, MO}|
||*Summer Intern, Washington University School of Medicine, Division of Public Health Sciences*|
||Created custom labor curves based on women in labor's individual characteristics. Obtained model estimates and 95% confidence intervals for the custom labor curves using bootstrap resampling methods.|


# Awards
\begin{tabbing}
2016\hspace*{1.3cm}\= Vanderbilt Big Biomedical Data Science Fellow\\
2016\>First Place, Government Statistics Section Student Data Challenge, ASA Joint Statistical Meeting\\
2016\>Second Place, Scientific and Public Affairs Advisory Committee Poster Competition, ASA Joint Statistical Meeting\\
2016\> Southern Startup Internship Program in Data Science (DataStart) Recipient\\
2016\>SAS Student Ambassador, SAS Global Forum 2016\\
2015\>First Place, Government Statistics Section Student Data Challenge, ASA Joint Statistical Meeting\\
2015\>Prezi Student Ambassador\\
2014\> SAS Student Scholar, PharmaSUG\\
2014\>SAS Student Ambassador, SAS Global Forum 2014\\
2013\> Best Contributed Paper in the Statistics and Data Analysis Section at SAS Global Forum\\
2013\> First Place, Student Research Competition, Applied Public Health Statistics, 141st APHA Annual Meeting\\
2013\>Ellis R. Ott Scholarship: ASQ Statistics Division \\
2013\>SAS Student Scholar, NESUG\\
2013\> SAS Student Ambassador, SAS Global Forum 2013\\
2012\>NIAF Jim Cantalupo Scholarship\\
2012\>Gertrude M. Cox Scholarship for Women in Statistics Honorable Mention\\
2008-2012\>UNC Public Service Scholar\\
2011\>Dunlevie Honors Undergraduate Research Award \\
2011-2012\>National Society of Leadership and Success\\
2010\>Programma Ponte Scholarship\\
2010\>Newman Scholar\\
2009-2012\> UNC Dean's List\\	
\end{tabbing}

# Invited Presentations
**SAS Global Forum 2016** \fn{Oral Presentation} 

> **Lucy D'Agostino McGowan**, Robert A. Greevy, Jr ["Integrating SAS? and R to Perform Optimal Propensity Score Matching."](http://support.sas.com/resources/papers/proceedings16/11420-2016.pdf)

**SAS Global Forum 2015** \fn{Oral Presentation}  

> **Lucy D'Agostino McGowan**, Alice Toll ["Using PROC SURVEYREG and PROC SURVEYLOGISTIC to Assess Potential Bias."](http://support.sas.com/resources/papers/proceedings15/3320-2015.pdf)

**SAS Global Forum 2014** \fn{Oral Presentation}  

> **Lucy D'Agostino McGowan**, Melody S. Goodman, Kimberly A. Kaphingst ["Using SAS/STAT® Software to Validate a Health Literacy Prediction Model in a Primary Care Setting."](http://support.sas.com/resources/papers/proceedings14/1494-2014.pdf)

# Contributed presentations

**ENAR 2017** \fn{Oral Presentation}  

> **Lucy D'Agostino McGowan**, Robert Alan Greevy, Jr, "Simplifying and Contextualizing Sensitivity to Unmeasured Confounding Tipping Point Analyses."

**ASA Joint Statistical Meeting 2016** \fn{Oral Presentation}

> Ryan Jarrett, **Lucy D'Agostino McGowan**, "Assessing the Association Between Accident Injury Severity and NCAP Car Safety Ratings."

**ASA Joint Statistical Meeting 2016** \fn{Poster} 

> **Lucy D'Agostino McGowan**, Robert A. Greevy, Jr, "Practical Guidance and Tools for Rule-Out Sensitivity to Unmeasured Confounding Analyses."
	
**ASA Joint Statistical Meeting 2015** \fn{Oral Presentation and Poster}  

> **Lucy D'Agostino McGowan**, Alice Toll, "Census Tract-Level Disparities: Examining Food Swamps and Food Deserts."

**141st American Public Health Association Annual Meeting 2013** \fn{Poster}  

> **Lucy D'Agostino McGowan**, Melody S. Goodman, "Developing County-Level Estimates of Racial Disparities in Obesity Using Multilevel Reweighted Regression."

**141st American Public Health Association Annual Meeting 2013** \fn{Oral Presentation}

> **Lucy D'Agostino McGowan**, Melody S. Goodman, "Small Areal Estimation of Racial Disparities in Diabetes Using Multilevel Reweighted Regression."

**SAS Analytics 2013** \fn{Poster}

> **Lucy D'Agostino McGowan**, Patrick J. McGowan, "Mining Through Resumes: Utilizing SAS to Increase Efficiency and Objectivity in the Hiring Process."

**Northeast SAS Users Group 2013** \fn{Poster}

> **Lucy D'Agostino McGowan** "SAS ® for Budgeting an Ideal Wedding"

**Northeast SAS Users Group 2013** \fn{Oral Presentation}

> **Lucy D'Agostino McGowan**, Melody S. Goodman,["Using PROC GLIMMIX and PROC SGPLOT to Demonstrate County-level Racial Disparities in Obesity in North Carolina."](https://www.researchgate.net/publication/272507933_Using_PROC_GLIMMIX_and_PROC_SGPLOT_to_Demonstrate_County-level_Racial_Disparities_in_Obesity_in_North_Carolina)

**SAS Global Forum 2013** \fn{Oral Presentation}

> **Lucy D'Agostino McGowan**, Melody S. Goodman, ["Multilevel Reweighted Regression Models to Estimate County-Level Racial Health Disparities Using PROC GLIMMIX."](http://support.sas.com/resources/papers/proceedings13/442-2013.pdf)


\section{Activities}
\textbf{Vanderbilt University}
\begin{tabbing}
2016-2017\hspace*{1.7cm}\=R-Ladies Nashville, co-founder\\
2016-2017\>  Graduate Student Council, President\\
2016-2017\> Biostatistics Graduate Student Association, Vice President\\
2015 \> Scholarship of Teaching and Learning, Scholar\\
2014-2015\> Graduate Student Council, Vice President of Social Affairs (2015), Committee member (2014)\\
2014-2015\> GRE Math Tutor\\
2013-2016\>American Statistical Association, Member\\
\end{tabbing}
\textbf{Washington University School of Medicine in St. Louis}
\begin{tabbing}
2013-2014 \hspace*{.8cm}\= American Public Health Association, Member, Abstract Reviewer\\
2013-2014\>Biostatistics and SAS tutor
\end{tabbing}
\textbf{University of North Carolina at Chapel Hill}
\begin{tabbing}
2011-2012\hspace*{.8cm}\=Carolina Dining Services, Student Manager\\
2011-2012\>Italian Club, President\\
2010-2011\>Information Technology Services, Walk-in Computing Consultant\\
2010-2011\>Newman Catholic Student Center, Director of Community Building\\
2010\>Daily Tar Heel Cartoonist\\
2009-2012\>Habitat for Humanity Volunteer\\
2008-2009\>Residence Hall Association, Craige Community Governor\\
2008-2011\>Inter-Faith Council Soup Kitchen Volunteer
\end{tabbing}

# Peer-reviewed publications 
> 